name: aeseverywhere
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/mervick/aes-everywhere

environment:
  sdk: '>=2.17.7 <3.0.0'

dependencies:
  encrypt: ^5.0.1
  crypto: ^3.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
